### ISSUE TITLE
Porosity pre-processing?

### ISSUE THREAD

**Issue by ThomasMGeo** [agilescientific/welly#111]
Porosity in PHIN and PHID logs sometimes comes in a format that is 0-1 or 0-100, is there a way to "pre-process" a whole data set, eg if max porosity is less than 1, multiply by 100, etc.

**Comment by rgmyr** [comment]
You can write this as a `lambda` (or a regular function) and pass it as a dict value in the `funcs` argument to `from_las` (both the `Well` and `Project` methods). For example:

```python
fractions_as_percents = lambda x: x*100. if np.nanmax(x) <= 1. else x

transforms = {c : fractions_as_percents for c in ['PHIN', 'PHID']}

project = welly.Project.from_las(path='/path/to/wells/*.las', funcs=transforms)
```
