### ISSUE TITLE
other uses for composite plot

### ISSUE THREAD

**Issue by alexcolyer** [agilescientific/welly#127]
Can the composite plot be used to plot other data, such as groundwater level time series?

**Comment by ThomasMGeo** [comment]
Do you have an example plot of what that would look like?

**Comment by ThomasMGeo** [comment]
Or a data example?

**Comment by EvanBianco** [comment]
Yes, @alexcolyer if you can describe the data structure(s) and or provide a sketch or a picture of the kind of thing you have in mind, then we can review what the options are.

**Comment by alexcolyer** [comment]
Hi,

What I am trying to make is something like the image below. Where the y-axis is the same for the time series and borehole log. I am not sure the composite plot will work as the data has a point for every depth, whereas I would like to plot a water level depth and time next to the log.

![welly and timeseries](https://user-images.githubusercontent.com/44571638/79637710-8758ef80-8179-11ea-9d42-4dc63ad18087.PNG)

**Comment by kwinkunks** [comment]
There are 2 tricks:

- set up the figure and its axes using `sharey=True`
- then give the axis to striplog to make its plot (`ax0` in the example)

There's an example of this kind of display in:

https://github.com/agile-geoscience/striplog/blob/master/tutorial/Striplog_expert.ipynb

![image](https://user-images.githubusercontent.com/1692372/79644010-870e2380-817c-11ea-923a-e6d1ac8157fa.png)

**Comment by EvanBianco** [comment]
The question seems to be answered. Closing.
