### ISSUE TITLE
LAS file loads with step = 0

### ISSUE THREAD

**Issue by kwinkunks** [agilescientific/welly#214]
This file loads but the curves have step = 0

https://raw.githubusercontent.com/mardani72/Synthetic_Seismogram/master/KK1.las

`lasio` has no trouble, so this is a `welly` bug.

**Comment by kwinkunks** [comment]
The problem is originally with the LAS. There's a point at which the depths **decrease**:

    [3849.3296, 3850.8536, 3849.482, 3849.6344]

`welly` checks that all the steps are the same (within some small tolerance) and then uses the median of the steps. But if they aren't all the same, `welly` sets the step to 0. Maybe this is not the best choice... could be `np.nan` or `None` or something else. Or it could make a smart guess (like throw out outliers and try again)... but of course there are some files that this won't be appropriate for. :thinking_face:

In any case, welly should throw a warning that there's an issue.

I think the safest thing to do is to resample, e.g. like so:

```
for mnemonic, curve in well.data.items():
    well.data[mnemonic] = curve.to_basis(step=0.1524)
```

This will resample all the curves to 0.1524 m (0.5 ft), which is what the step should be.

**Comment by kinverarity1** [comment]
As a user, I think the best way to handle these files is on loading them, with an option to say "ensure the index is regularly-spaced". Most people would say yes to that, I suspect.
